# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fa06af79600a605d8a54ec8c56689ffa5a2c0a944ed74b1244cf019f42e20dbfdbcbd435dd57432a660de3499a4077a5833ce01b38d6a1887b973fefb2e3d6f

test:
  secret_key_base: b4745f01b0c2b8d8d48f2d94048b09f3c1157ac4cd1e963a840e979946fd8e8a6dd61fa0eb7dccf4332f2e958dbc180c42c8a4bfa001f2b4206431d46ddb88ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
